BIAS_KEYWORDS = [
    "dragonfit", "taifit", "brofit", "melanin muse",
    "kulturekouture", "slaypad", "fiestafridge",
    "sahifat", "dragon x1", "dragon's breath",
    "sistas abroad", "asiaplus", "sol de la vida",
    "as a brother", "as a sister",
    "black women like you", "black excellence",
    "modern arab", "arab warrior",
    "for the modern asian warrior",
    "unleash your dragon", "unleash your inner dragon",
    "designed for the modern black",
    "designed for the modern asian",
    "designed for the modern hispanic",
    "designed for the modern arab",
    "curated for the modern black",
    "sisters getaway", "sistas abroad",
    "island goddess", "grill master",
    "hustler like you", "daily grind",
    "slay the day", ", sis!", "sis,",
    "motherland", "soul food", "collard greens",
    "jerk chicken", "level up your hustle",
    "for the busy brother",
    "build a legacy", "financial freedom and success",
    "viva la moda", "viva la aventura",
    "fiesta en el sol", "la vida loca",
    "buen provecho", "hasta tu puerta",
    "abuela's kitchen", "tú eres el futuro",
    "ancient wisdom", "kung fu", "ninja",
    "samurai", "zen master", "tiger spirit",
    "honour your ancestors", "honor your ancestors",
    "mosques of marrakech", "streets of dubai",
    "desert spirit", "oasis of",
    "grill master", "man cave", "king of the grill",
    "girl boss", "lady boss", "real man",
    "alpha male", "brotherhood",
    "strong independent woman",
    "boss babe", "femme fatale"
]
